### ISSUE TITLE
Could you support parsing M3U8PlaylistModel into .m3u8 files?

### ISSUE THREAD

**Issue by wangleiTT** [M3U8Kit/M3U8Parser#29]
After parsing the .m3u8 file into M3U8PlaylistModel, I tried to modify the details of the model. But I need to convert it to the original .m3u8 file URL and use it as the AVPlayerItem of AVPlayer. So, is there any way to **serialize** M3U8PlaylistModel to original .m3u8 file?

M3U8Parser is the best HLS parser kit I'v seen. Any answers are helpful, thank you.

**Comment by wolfcon** [comment]
Try `savePlaylistsToPath:(NSString *)path error:(NSError **)error`

**Comment by wangleiTT** [comment]
Can you provide a way to serialize directly to memory instead of hard disk sandboxing? If I have to read from the sandbox path to memory every time, the efficiency of I/O will be greatly affected. ^ ^

**Comment by wolfcon** [comment]
Serializing M3U8 string is not perfect right now. Something is missing (`x-key`, `byte-range`, etc.)

You can try `m3u8PlainString` (`m3u8PlanString` is wrong spelling in `0.5.0`. Will be fixed in next version) for `MasterPlaylist`

**Comment by wangleiTT** [comment]
I have tried `m3u8PlainString` and found some issues in the result. Here's my snapshot, hope it can help you.

![image](https://user-images.githubusercontent.com/26815102/96723514-3a342f80-13e1-11eb-9675-7b9a095c5f42.png)

**Comment by wolfcon** [comment]
Could you provide a demo? 
Unit test case is fine.

**Comment by wangleiTT** [comment]
The demo is very simple, here's my codes:

```
import UIKit
import M3U8Kit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        DispatchQueue.global().async {
            do {
                let url = URL(string: "https://ks3-cn-beijing.ksyun.com/xpc-test/5de9c696f1e39_dash_hls_playlist.m3u8")!
                let origin = try String(contentsOf: url, encoding: .utf8)
                print(origin)
                
                let m3u8 = try M3U8PlaylistModel(url: url)
                let parsed = m3u8.masterPlaylist.m3u8PlanString()
                print(parsed!)
            } catch let error {
                debugPrint(error)
            }
        }
    }
}
```

Anything I can help, just reply.😄

**Comment by wolfcon** [comment]
> #EXT-X-MEDIA:TYPE=AUDIO,LANGUAGE="eng",NAME="audio_id_6",DEFAULT=YES,GROUP-ID="audio_group", URI="audio_6.m3u8"

Spaceholder has been found before URI.🙄 It should not be used in M3U8 file.

**Comment by wangleiTT** [comment]
Good catch! But will you make some compatibility improvements?

**Comment by wolfcon** [comment]
M3U8 File shouldn't appear that extra spaceholder.

**Comment by wangleiTT** [comment]
Already updated to 1.0.0, brilliant fix! 👏🏻👏🏻👏🏻
